# Usign the Clean Blog theme

title: Stéphane Mallat's 60 birthday conference
author: Joan Bruna and Gabriel Peyré
email: gabriel.peyre@ens.fr
description: Stéphane Mallat's 60 birthday conference
baseurl: ""
url: "mallat60.github.io"
github_username:  gpeyre
twitter_username: gabrielpeyre

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]

name: 
gems:
  - jekyll-feed
  - jekyll-paginate
